import React from "react";
import { createRoot } from "react-dom/client";
import HomePage from "./app/page";
import "./app/globals.css";
import "./app/design-2026.css";
import "./app/reference-feed.css";
import "./app/reference-chat.css";
import "./app/reference-story.css";
import "./app/reference-discover.css";
import "./app/reference-account.css";
import "./app/tokens.css";
import "./app/components.css";
createRoot(document.getElementById("root")!).render(<HomePage/>);
