"use client";
import { useEffect, useMemo, useRef, useState, type FormEvent, type ChangeEvent } from "react";
import { ArrowLeft, ArrowUp, Bell, Bookmark, Camera, Check, ChevronLeft, ChevronRight, CircleAlert, Clock3, Image as ImageIcon, MapPin, MessageCircle, MoreHorizontal, Pause, Play, Plus, Repeat2, Search, Send, Share2, ShoppingBag, ThumbsUp, UserRound, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PostMedia } from "@/components/nexo-post-media";
import { useNexoAppearance } from "@/components/nexo-appearance";
import { featureFlags } from "@/lib/feature-flags";
import { useDemo, uid, initials, fileData, dayKey } from "@/lib/demo-store";
import { rankPosts, type Post, type PostKind, type Story } from "@/lib/demo-data";
export type Quota={notify:number;reporte:number};
export function Avatar({name,small=false}:{name:string;small?:boolean}) {return <span className={"avatar"+(small?" small":"")}>{initials(name)}</span>;}
export function linkParts(value:string){return value.split(/(https?:\/\/[^\s]+)/g).map((p,i)=>/^https?:\/\//.test(p)?<a href={p} key={i} target="_blank" rel="noopener noreferrer">{p}</a>:<span key={i}>{p}</span>);}
export function elapsed(at?:number){const n=Math.max(0,Math.floor((Date.now()-(at||Date.now()))/60000));return n<1?"ahora":n<60?n+" min":n<1440?Math.floor(n/60)+" h":Math.floor(n/1440)+" d";}
export function FollowButton({handle}:{handle:string}){const {state,follow}=useDemo();const active=state.following.includes(handle);return <button className={active?"following-button":"follow-button"} aria-pressed={active} onClick={()=>follow(handle)}>{active?"Siguiendo":"Seguir"}</button>;}
export function StoriesRail({onStory,onCreate}:{onStory:(s:Story)=>void;onCreate:()=>void}){
 const {state}=useDemo();return <section className="stories-block"><div className="section-title"><h2>Dumps <small>· 3 horas en el campus</small></h2><span className="stories-all">Toda la comunidad</span></div><div className="stories-scroll"><button className="story" onClick={onCreate}><span className="story-avatar mine"><span><Plus size={24}/></span></span><strong>Tu Dump</strong></button>{state.stories.map(s=><button className="story" key={s.id} onClick={()=>onStory(s)}><span className="story-avatar"><span>{s.media&&s.mediaType!=="video"?<img src={s.media} alt=""/>:s.initials}</span></span><strong>{s.author}</strong></button>)}</div></section>;
}
export function PostCard({post,onContact,onDetail,onAuthor,detail=false}:{post:Post;onContact:(name:string)=>void;onDetail:(id:string)=>void;onAuthor:(handle:string)=>void;detail?:boolean}){
 const {state,update}=useDemo();const [comment,setComment]=useState("");const [parent,setParent]=useState<string|undefined>();const [burst,setBurst]=useState(false);
 const {enabled:designEnabled}=useNexoAppearance();const gesturesEnabled=designEnabled&&featureFlags.gestures2026;
 function toggle(key:"liked"|"saved"|"reposted"){update(s=>({...s,posts:s.posts.map(p=>p.id===post.id?{...p,[key]:!p[key]}:p)}));if(key==="saved")toast(post.saved?"Quitado de guardados":"Guardado en tu perfil");}
 function add(e:FormEvent){e.preventDefault();if(!comment.trim())return;update(s=>({...s,posts:s.posts.map(p=>p.id===post.id?{...p,comments:[...p.comments,{id:uid(),author:s.profile.name,text:comment.trim(),parentId:parent}]}:p)}));setComment("");setParent(undefined);}
 async function share(){const url=new URL(location.href);url.hash="post/"+post.id;try{if(navigator.share)await navigator.share({title:post.title,url:url.href});else{await navigator.clipboard.writeText(url.href);toast("Enlace copiado");}}catch(error){if((error as Error).name!=="AbortError")toast.error("No se pudo compartir el enlace.");}}
 function doubleUp(){if(!post.liked)toggle("liked");setBurst(true);setTimeout(()=>setBurst(false),500);}
 function comments(parentId?:string,depth=0):React.ReactNode{return post.comments.filter(c=>c.parentId===parentId).map(c=><div key={c.id} className={depth?"comment-reply":""}><div className="comment"><Avatar name={c.author}/><div><b>{c.author}</b><p>{linkParts(c.text)}</p><button className="comment-reply-button" onClick={()=>setParent(c.id)}>Responder</button></div></div>{depth<8&&comments(c.id,depth+1)}</div>);}
 return <article className={"post-card "+post.kind} data-post-id={post.id}>
 {(post.kind==="notify"||post.kind==="reporte")&&<div className="post-strip">{post.kind==="notify"?<Zap size={16}/>:<CircleAlert size={16}/>}<span className="post-type-label">{post.kind==="notify"?"Notify":"Reporte · ayuda"}</span><span>Para toda UPA</span></div>}
 <div className="post-head"><button className="author-avatar" aria-label={"Ver perfil de "+post.author} onClick={()=>onAuthor(post.handle)}><Avatar name={post.author}/></button><div><button className="author-name" onClick={()=>onAuthor(post.handle)}>{post.own?state.profile.name:post.author}</button><small>{post.handle} · {elapsed(post.createdAt)}</small></div>{!post.own&&<FollowButton handle={post.handle}/>}<DropdownMenu><DropdownMenuTrigger asChild><button className="more-button" aria-label={"Opciones de "+post.author}><MoreHorizontal size={20}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={share}>Compartir enlace</DropdownMenuItem><DropdownMenuItem onClick={()=>{update(s=>({...s,hidden:[...s.hidden,post.id]}));toast("Publicación ocultada",{action:{label:"Deshacer",onClick:()=>update(s=>({...s,hidden:s.hidden.filter(id=>id!==post.id)}))}});}}>Ocultar de mi feed</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
 <div className="post-content"><h3><button onClick={()=>onDetail(post.id)}>{post.title}</button></h3><p>{linkParts(post.body)}</p>{post.location&&<span className="location"><MapPin size={14}/>{post.location}</span>}</div>
 <PostMedia post={post} burst={burst} gesturesEnabled={gesturesEnabled} onDoubleUp={doubleUp}/>
 {post.source&&<a className="photo-credit" href={post.source.url} target="_blank" rel="noopener noreferrer">{post.source.title}</a>}
 {post.kind==="venta"&&<div className="sale-footer"><span><ShoppingBag size={16}/>{post.category}</span><button onClick={()=>onContact(post.author)}>Contactar vendedor</button></div>}
 <div className="post-actions"><button className={post.liked?"selected":""} aria-label={post.liked?"Quitar Up":"Dar Up"} aria-pressed={!!post.liked} onClick={()=>toggle("liked")}><ArrowUp size={22}/><strong>{post.ups+Number(!!post.liked)}</strong><span>Up!</span></button><button aria-label="Ver comentarios" onClick={()=>onDetail(post.id)}><MessageCircle size={20}/><strong>{post.comments.length}</strong></button><button className={post.reposted?"selected":""} aria-label={post.reposted?"Deshacer repost":"Repostear"} aria-pressed={!!post.reposted} onClick={()=>toggle("reposted")}><Repeat2 size={21}/><strong>{post.reposts+Number(!!post.reposted)}</strong></button><button className={post.saved?"selected":""} aria-label={post.saved?"Quitar de guardados":"Guardar"} aria-pressed={!!post.saved} onClick={()=>toggle("saved")}><Bookmark size={20} fill={post.saved?"currentColor":"none"}/></button><button aria-label="Compartir publicación" onClick={share}><Share2 size={19}/></button></div>
 {detail&&<section className="comments-panel"><h4>Comentarios · {post.comments.length}</h4>{comments()}{!post.comments.length&&<p className="empty-text">Inicia la conversación.</p>}{parent&&<button className="reply-indicator" onClick={()=>setParent(undefined)}>Respondiendo a un comentario <X size={16}/></button>}<form onSubmit={add}><input aria-label="Nuevo comentario" placeholder="Escribe un comentario…" value={comment} onChange={e=>setComment(e.target.value)} maxLength={2000}/><button disabled={!comment.trim()} aria-label="Enviar comentario"><Send size={18}/></button></form></section>}
 </article>;
}
type Actions={onContact:(name:string)=>void;onDetail:(id:string)=>void;onAuthor:(handle:string)=>void};
export function FeedView({onCreate,onStory,...actions}:Actions&{onCreate:(kind:PostKind|"dump")=>void;onStory:(s:Story)=>void}){
 const {state}=useDemo();const [mode,setMode]=useState("para-ti");const posts=rankPosts(state.posts.filter(p=>!state.hidden.includes(p.id)).map(p=>({...p,isFriend:state.following.includes(p.handle),ageMinutes:(Date.now()-(p.createdAt||Date.now()))/60000})),mode==="siguiendo"?"amigos":"para-ti");
 return <><div className="demo-note">Demo interactiva · los cambios se guardan en este navegador</div><StoriesRail onStory={onStory} onCreate={()=>onCreate("dump")}/><section className="compose-card"><button className="compose-top" onClick={()=>onCreate("post")}><Avatar name={state.profile.name}/><span>¿Qué está pasando en UPA?</span><ImageIcon size={20}/></button><div className="compose-options"><button onClick={()=>onCreate("post")}><ImageIcon size={18}/>Post</button><button onClick={()=>onCreate("notify")}><Zap size={18}/>Notify <em>{2-state.quota.notify}/2</em></button><button onClick={()=>onCreate("reporte")}><CircleAlert size={18}/>Reporte <em>{2-state.quota.reporte}/2</em></button></div></section><Tabs value={mode} onValueChange={setMode} className="feed-tab-root"><TabsList variant="line" className="feed-tabs"><TabsTrigger value="para-ti">Para ti</TabsTrigger><TabsTrigger value="siguiendo">Siguiendo</TabsTrigger></TabsList><TabsContent value={mode}><div className="posts">{posts.map(p=><PostCard post={p} key={p.id} {...actions}/>)}{!posts.length&&<p className="empty-text">Aquí aparecerán publicaciones de las personas que sigas.</p>}</div></TabsContent></Tabs></>;
}
export function ExploreView({onCreate,...actions}:Actions&{onCreate:(kind:PostKind)=>void}){
 const {state}=useDemo();const [query,setQuery]=useState("");const [tab,setTab]=useState("destacados");const q=query.toLocaleLowerCase("es");
 const posts=state.posts.filter(p=>!state.hidden.includes(p.id)&&[p.title,p.body,p.author,p.category||""].join(" ").toLocaleLowerCase("es").includes(q));
 const people=Array.from(new Map(state.posts.filter(p=>!p.own).map(p=>[p.handle,p])).values()).filter(p=>(p.author+" "+p.program).toLocaleLowerCase("es").includes(q));
 return <><div className="feature-view"><div className="feature-search"><Search size={20}/><input type="search" aria-label="Buscar en UPA" placeholder="Buscar personas, publicaciones, productos" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><Tabs value={tab} onValueChange={setTab} className="feed-tab-root"><TabsList variant="line" className="feed-tabs"><TabsTrigger value="destacados">Descubrir</TabsTrigger><TabsTrigger value="personas">Personas</TabsTrigger><TabsTrigger value="mercado">Mercado</TabsTrigger></TabsList><TabsContent value="destacados">{posts.map(p=><PostCard post={p} key={p.id} {...actions}/>)}{!posts.length&&<p className="empty-text">No hay resultados para “{query}”.</p>}</TabsContent><TabsContent value="personas"><div className="community-list feature-view">{people.map(p=><article key={p.handle}><button className="author-avatar" onClick={()=>actions.onAuthor(p.handle)} aria-label={"Ver perfil de "+p.author}><Avatar name={p.author}/></button><div><h3>{p.author}</h3><p>{p.program}</p><small>{p.handle}</small></div><FollowButton handle={p.handle}/></article>)}{!people.length&&<p className="empty-text">No encontramos personas.</p>}</div></TabsContent><TabsContent value="mercado"><div className="feature-view"><div className="market-heading"><h2>Entre estudiantes</h2><button className="button-secondary" onClick={()=>onCreate("venta")}><Plus size={18}/>Vender</button></div><div className="product-grid">{posts.filter(p=>p.kind==="venta").map(p=><article key={p.id}><button className="product-image" onClick={()=>actions.onDetail(p.id)} aria-label={"Ver "+p.title}>{p.image?<img src={p.image} alt={p.title}/>:<ShoppingBag size={32}/>}</button><div className="product-info"><strong>{p.price}</strong><h4>{p.title}</h4><p>{p.author}</p><button onClick={()=>actions.onContact(p.author)}>Enviar mensaje</button></div></article>)}</div>{!posts.some(p=>p.kind==="venta")&&<p className="empty-text">No hay productos para esta búsqueda.</p>}<p className="form-footnote market-footnote">Acuerda las entregas en espacios públicos del campus.</p></div></TabsContent></Tabs></>;
}
export function ProfileView({handle,...actions}:Actions&{handle:string|null}){
 const {state,update}=useDemo();const own=!handle||handle==="@tu.perfil";const person=state.posts.find(p=>p.handle===handle);const name=own?state.profile.name:person?.author||"Perfil";const [edit,setEdit]=useState(false);const [tab,setTab]=useState("posts");
 const authored=state.posts.filter(p=>own?p.own:p.handle===handle);const visible=tab==="guardados"?state.posts.filter(p=>p.saved):tab==="reposts"?state.posts.filter(p=>p.reposted):authored;
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);update(s=>({...s,profile:{name:String(data.get("name")).trim(),bio:String(data.get("bio")).trim(),program:String(data.get("program")).trim(),note:String(data.get("note")).trim()}}));setEdit(false);toast.success("Perfil actualizado");}
 return <><section className="profile-header"><div className="profile-top"><Avatar name={name}/>{own?<button className="button-secondary" onClick={()=>setEdit(true)}>Editar perfil</button>:<><FollowButton handle={handle||""}/><button className="button-secondary" onClick={()=>actions.onContact(name)}>Mensaje</button></>}</div><h2>{name}</h2><p className="profile-handle">{own?"@tu.perfil":handle}</p><p>{own?state.profile.bio:"Compartiendo ideas y momentos en la comunidad UPA."}</p><span className="profile-program">{own?state.profile.program:person?.program}</span><div className="profile-stats"><span><b>{authored.length}</b> publicaciones</span>{own&&<span><b>{state.following.length}</b> siguiendo</span>}</div>{own&&state.profile.note&&<div className="profile-note"><MessageCircle size={16}/>{state.profile.note}</div>}</section><Tabs value={tab} onValueChange={setTab} className="feed-tab-root"><TabsList variant="line" className="feed-tabs"><TabsTrigger value="posts">Publicaciones</TabsTrigger><TabsTrigger value="media">Fotos</TabsTrigger>{own&&<><TabsTrigger value="reposts">Reposts</TabsTrigger><TabsTrigger value="guardados">Guardados</TabsTrigger></>}</TabsList><TabsContent value={tab}>{tab==="media"?<div className="profile-grid">{authored.filter(p=>p.image).map(p=><button key={p.id} onClick={()=>actions.onDetail(p.id)}>{p.mediaType==="video"?<video src={p.image} muted preload="metadata"/>:<img src={p.image} alt={p.title}/>}</button>)}</div>:visible.map(p=><PostCard key={p.id} post={p} {...actions}/>)}{(tab==="media"?!authored.some(p=>p.image):!visible.length)&&<p className="empty-text">{tab==="guardados"?"Guarda una publicación para encontrarla aquí.":tab==="reposts"?"Tus reposts aparecerán aquí.":"Todavía no hay publicaciones."}</p>}</TabsContent></Tabs><Dialog open={edit} onOpenChange={setEdit}><DialogContent className="edit-dialog"><DialogHeader><DialogTitle>Editar perfil</DialogTitle><DialogDescription>Tu identidad en esta demo de Nexo.</DialogDescription></DialogHeader><form className="auth-form" onSubmit={save}><label>Nombre<input name="name" defaultValue={state.profile.name} required maxLength={60}/></label><label>Carrera<input name="program" defaultValue={state.profile.program} maxLength={80}/></label><label>Biografía<textarea name="bio" defaultValue={state.profile.bio} maxLength={160}/></label><label>Nota para tus chats<input name="note" defaultValue={state.profile.note} maxLength={60}/></label><button className="button-primary">Guardar cambios</button></form></DialogContent></Dialog></>;
}
export function NotificationsView({onDetail}:{onDetail:(id:string)=>void}){
 const {state,update}=useDemo();return <><div className="view-toolbar"><span>Actividad de la demo</span><button className="text-button" onClick={()=>update(s=>({...s,notifications:s.notifications.map(n=>({...n,read:true}))}))}>Marcar como leídas</button></div><div className="notification-list">{state.notifications.map(n=><button key={n.id} className={n.read?"":"unread"} onClick={()=>{update(s=>({...s,notifications:s.notifications.map(x=>x.id===n.id?{...x,read:true}:x)}));if(n.postId)onDetail(n.postId);}}><span className="notification-symbol"><Bell size={20}/></span><p><b>{n.text}</b><small>{n.detail}</small></p><em>{elapsed(n.at)}</em>{!n.read&&<i className="unread-dot"/>}</button>)}</div><p className="empty-text">Las alertas de esta prueba son locales, no notificaciones push.</p></>;
}
async function duration(file:File):Promise<number>{return new Promise((resolve,reject)=>{const video=document.createElement("video");const url=URL.createObjectURL(file);const done=()=>{URL.revokeObjectURL(url);video.removeAttribute("src");};video.onloadedmetadata=()=>{const d=video.duration;done();Number.isFinite(d)?resolve(d):reject(new Error("Duración no válida"));};video.onerror=()=>{done();reject(new Error("No se pudo leer el video"));};video.src=url;});}
export function PublishDialog({open,initialKind,onClose,onDone}:{open:boolean;initialKind:PostKind|"dump";onClose:()=>void;onDone:()=>void}){
 const {state,update}=useDemo();const [kind,setKind]=useState<PostKind|"dump">(initialKind);const [title,setTitle]=useState("");const [body,setBody]=useState("");const [location,setLocation]=useState("");const [price,setPrice]=useState("");const [category,setCategory]=useState("Comida");const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(open){setKind(initialKind);setTitle(state.draft.title);setBody(state.draft.body);setError("");}},[open,initialKind]);
 useEffect(()=>{if(!file){setPreview("");return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 const options=[{id:"post",name:"Post",icon:ImageIcon,note:"Ilimitados"},{id:"notify",name:"Notify",icon:Zap,note:(2-state.quota.notify)+"/2 hoy"},{id:"reporte",name:"Reporte",icon:CircleAlert,note:(2-state.quota.reporte)+"/2 hoy"},{id:"venta",name:"Venta",icon:ShoppingBag,note:"Mercado"},{id:"dump",name:"Dump",icon:Camera,note:"Dura 3 h"}] as const;
 async function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];e.target.value="";if(!f)return;setError("");if(!/^image\/(jpeg|png|webp|gif)$|^video\/(mp4|webm|quicktime)$/.test(f.type)){setError("Selecciona una foto JPG, PNG, WebP, GIF o un video MP4, WebM o MOV.");return;}if(f.size>(f.type.startsWith("video")?30:10)*1024*1024){setError("La foto admite hasta 10 MB; el video, hasta 30 MB.");return;}setBusy(true);try{if(f.type.startsWith("video")&&await duration(f)>(kind==="dump"?25:30))throw new Error("El video supera "+(kind==="dump"?25:30)+" segundos.");setFile(f);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function publish(e:FormEvent){e.preventDefault();if(busy)return;const limited=kind==="notify"||kind==="reporte";if(limited&&state.quota.day===dayKey()&&state.quota[kind]>=2){setError("Ya usaste tus dos "+kind+" de hoy.");return;}if(!body.trim()&&!file){setError("Escribe algo o adjunta un archivo.");return;}if(kind==="venta"&&(!price||Number(price)<=0)){setError("Escribe un precio válido.");return;}setBusy(true);setError("");try{
 const media=file?await fileData(file):undefined;const id=uid();const now=Date.now();const mediaType=file?.type.startsWith("video")?"video":"image";
 update(s=>{const quota={...s.quota};if(limited){if(quota[kind]>=2)return s;quota[kind]++;}
 const base={...s,quota,draft:{kind:"post",title:"",body:""}};
 if(kind==="dump")return {...base,stories:[{id,author:s.profile.name,initials:initials(s.profile.name),text:body.trim(),tone:"green",remainingMinutes:180,expiresAt:now+3*3600000,media,mediaType,own:true},...s.stories]};
 const post:Post={id,kind,author:s.profile.name,handle:"@tu.perfil",initials:initials(s.profile.name),program:s.profile.program,ageMinutes:0,createdAt:now,title:title.trim()||(kind==="reporte"?"Reporte de la comunidad":kind==="venta"?"Producto de la comunidad":kind==="notify"?"Aviso para UPA":"Publicación de "+s.profile.name),body:body.trim(),location:location.trim(),image:media,mediaType,price:kind==="venta"?"$"+Number(price).toFixed(2):undefined,category:kind==="venta"?category:undefined,ups:0,reposts:0,comments:[],isFriend:true,tags:[],own:true};
 return {...base,posts:[post,...s.posts],notifications:[{id:uid(),text:kind==="notify"?"Tu Notify está publicado":kind==="reporte"?"Tu reporte está publicado":"Publicación guardada",detail:limited?"En la app conectada lo verá todo el campus.":"Prueba local guardada en este navegador.",postId:id,read:false,at:now},...s.notifications]};});
 setTitle("");setBody("");setFile(null);setPrice("");setLocation("");onClose();onDone();toast.success(kind==="dump"?"Dump compartido por 3 horas":"Publicación creada");
 }catch{setError("No se pudo preparar el archivo. Prueba uno más pequeño.");}finally{setBusy(false);}}
 function close(){update(s=>({...s,draft:{kind,title,body}}));onClose();}
 return <Dialog open={open} onOpenChange={v=>{if(!v)close();}}><DialogContent className="publish-dialog"><DialogHeader><DialogTitle>Crear publicación</DialogTitle><DialogDescription>{kind==="post"?"Visible en el feed. En la app conectada solo se avisará a tus amigos.":kind==="dump"?"Un momento para todo el campus. Desaparece en 3 horas.":"Comparte algo útil con la comunidad."}</DialogDescription></DialogHeader><form className="publish-form" onSubmit={publish}><div className="publish-kinds">{options.map(({id,name,icon:Icon,note})=><button type="button" key={id} aria-pressed={kind===id} className={kind===id?"active":""} onClick={()=>{setKind(id);setFile(null);setError("");}}><Icon size={20}/><b>{name}</b><small>{note}</small></button>)}</div>{kind!=="dump"&&<input aria-label="Título" placeholder="Título (opcional)" value={title} onChange={e=>setTitle(e.target.value)} maxLength={120}/>}<textarea aria-label="Contenido de la publicación" placeholder="¿Qué quieres compartir?" value={body} onChange={e=>setBody(e.target.value)} maxLength={4000}/><span className="character-count">{body.length}/4000</span>{kind==="venta"&&<div className="form-two"><input type="number" min=".01" step=".01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Precio en MXN" aria-label="Precio"/><Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="Categoría"><SelectValue/></SelectTrigger><SelectContent>{["Comida","Material","Servicios"].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div>}{kind!=="dump"&&<input aria-label="Lugar" placeholder="Lugar (opcional)" value={location} onChange={e=>setLocation(e.target.value)} maxLength={120}/>}<input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" onChange={choose}/><div className="media-actions"><button type="button" disabled={busy} onClick={()=>fileRef.current?.click()}><ImageIcon size={18}/>Foto o video</button><span>Video ≤ {kind==="dump"?25:30} s</span></div>{file&&<div className="upload-preview">{file.type.startsWith("video")?<video src={preview} controls playsInline/>:<img src={preview} alt="Vista previa"/>}<button type="button" aria-label="Quitar archivo" onClick={()=>setFile(null)}><X size={18}/></button></div>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button-primary" disabled={busy||(kind==="notify"&&state.quota.notify>=2)||(kind==="reporte"&&state.quota.reporte>=2)}>{busy?"Preparando…":kind==="dump"?"Compartir Dump":"Publicar"}</button><p className="form-footnote">Prueba local. Notify y Reporte: 2 de cada uno al día, sin acumular.</p></form></DialogContent></Dialog>;
}
export function StoryViewer({storyId,onClose,onReply}:{storyId:string|null;onClose:()=>void;onReply:(name:string)=>void}){
 const {state}=useDemo();const [index,setIndex]=useState(0);const [progress,setProgress]=useState(0);const [paused,setPaused]=useState(false);const [seconds,setSeconds]=useState(7);const video=useRef<HTMLVideoElement>(null);const touch=useRef(0);const stories=state.stories;const story=stories[index];
 useEffect(()=>{if(storyId){const i=stories.findIndex(s=>s.id===storyId);setIndex(Math.max(0,i));setProgress(0);setPaused(false);}},[storyId]);
 useEffect(()=>{setProgress(0);setSeconds(7);},[index]);
 useEffect(()=>{if(paused)video.current?.pause();else video.current?.play().catch(()=>{});},[paused,index]);
 useEffect(()=>{if(!storyId||paused)return;const timer=setInterval(()=>{if(document.hidden)return;setProgress(p=>Math.min(100,p+100/(seconds*10)));},100);return()=>clearInterval(timer);},[storyId,paused,index,seconds]);
 useEffect(()=>{if(progress>=100){if(index+1<stories.length)setIndex(i=>i+1);else onClose();}},[progress]);
 function move(delta:number){if(index+delta<0)return;if(index+delta>=stories.length)onClose();else setIndex(i=>i+delta);}
 return <Dialog open={!!storyId} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="story-dialog" showCloseButton={false} onTouchStart={e=>{touch.current=e.touches[0].clientX;}} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>50)move(delta<0?1:-1);}}><DialogHeader className="sr-only"><DialogTitle>Dump de {story?.author}</DialogTitle><DialogDescription>Historia temporal de la comunidad</DialogDescription></DialogHeader>{story?<><div className="story-progress">{stories.map((s,i)=><div key={s.id}><span style={{width:(i<index?100:i===index?progress:0)+"%"}}/></div>)}</div><div className="story-top"><Avatar name={story.author}/><div><b>{story.author}</b><small>{Math.max(1,Math.ceil(((story.expiresAt||0)-Date.now())/60000))} min restantes</small></div><button aria-label={paused?"Reanudar historia":"Pausar historia"} onClick={()=>setPaused(!paused)}>{paused?<Play size={20}/>:<Pause size={20}/>}</button><button aria-label="Cerrar historia" onClick={onClose}><X size={24}/></button></div>{story.media&&<div className="story-media">{story.mediaType==="video"?<video ref={video} src={story.media} autoPlay muted playsInline controls onLoadedMetadata={e=>setSeconds(Math.min(25,e.currentTarget.duration)||7)} onEnded={()=>move(1)}/>:<img src={story.media} alt={story.text||"Dump de "+story.author}/>}</div>}<p className="story-copy">{story.text}</p><div className="story-controls"><button aria-label="Historia anterior" disabled={!index} onClick={()=>move(-1)}><ChevronLeft/></button><button aria-label="Historia siguiente" onClick={()=>move(1)}><ChevronRight/></button></div><div className="story-bottom"><span>Visible 3 horas · toda UPA{story.source&&<> · <a href={story.source.url} target="_blank" rel="noopener noreferrer">{story.source.title}</a></>}</span><button onClick={()=>{onReply(story.author);onClose();}}>Responder <Send size={18}/></button></div></>:<p>Esta historia ya no está disponible.</p>}</DialogContent></Dialog>;
}
